AWSTemplateFormatVersion: 2010-09-09
Description: access test
Resources:
  DDBT10HT3:
    Type: 'AWS::DynamoDB::Table'
    Properties:
      TableName: Music
      AttributeDefinitions:
        - AttributeName: Artist
          AttributeType: S
        - AttributeName: SongTitle
          AttributeType: S
        - AttributeName: AlbumTitle
          AttributeType: S
      KeySchema:
        - AttributeName: Artist
          KeyType: HASH
        - AttributeName: SongTitle
          KeyType: RANGE
      ProvisionedThroughput:
        ReadCapacityUnits: 1
        WriteCapacityUnits: 1
      LocalSecondaryIndexes:
        - IndexName: AlbumTitleIndex
          KeySchema:
            - AttributeName: Artist
              KeyType: HASH
            - AttributeName: AlbumTitle
              KeyType: RANGE
          Projection:
            ProjectionType: KEYS_ONLY
