name: "main actions"

on: [push]

jobs:
  lint-api:
    runs-on: ubuntu-latest
    name: lint api action
    steps:
    - name: Checkout
      uses: actions/checkout@v2-beta
    - name: catReadme
      run: cat ./README.md
    - name: echo
      run: echo "TODO:lintチェックを走らせる"
  lint-front:
    runs-on: ubuntu-latest
    name: lint front action
    steps:
    - name: Checkout
      uses: actions/checkout@v2-beta
    - name: catReadme
      run: cat ./README.md
    - name: echo
      run: echo "TODO:lintチェックを走らせる"
  lint-infra:
    runs-on: ubuntu-latest
    name: lint infra action
    steps:
    - name: Checkout
      uses: actions/checkout@v2-beta
    - name: catReadme
      run: cat ./README.md
    - name: echo
      run: echo "TODO:lintチェックを走らせる"
  build-and-test-api:
    runs-on: ubuntu-latest
    name: build and test api action
    steps:
    - name: Checkout
      uses: actions/checkout@v2-beta
    - name: echo
      run: echo "TODO:build からの test コードを走らせる"
  build-and-test-front:
    runs-on: ubuntu-latest
    name: build and test front action
    steps:
    - name: Checkout
      uses: actions/checkout@v2-beta
    - name: echo
      run: echo "TODO:build からの test コードを走らせる"
  build-and-test-infra:
    runs-on: ubuntu-latest
    name: build and test infra action
    steps:
    - name: Checkout
      uses: actions/checkout@v2-beta
    - name: echo
      run: echo "TODO:build からの test コードを走らせる"

