name: "main actions"

on: [push]

jobs:
  lint-api:
    runs-on: ubuntu-latest
    name: lint api action
    steps:
    - name: Checkout
      uses: actions/checkout@v2-beta
    - name: cd api
      run: cd ./packages/api/
    - name: npm i
      run: npm i
    - name: lint
      run: npm run lint
  lint-front:
    runs-on: ubuntu-latest
    name: lint front action
    steps:
    - name: Checkout
      uses: actions/checkout@v2-beta
    - name: cd front
      run: cd ./packages/front/
    - name: npm i
      run: npm i
    - name: lint
      run: npm run lint
  build-and-test-api:
    runs-on: ubuntu-latest
    name: build and test api action
    steps:
    - name: Checkout
      uses: actions/checkout@v2-beta
    - name: cd api
      run: cd ./packages/api/
    - name: npm i
      run: npm i
    - name: lint
      run: npm run build
  build-and-test-front:
    runs-on: ubuntu-latest
    name: lint front action
    steps:
    - name: Checkout
      uses: actions/checkout@v2-beta
    - name: cd front
      run: cd ./packages/front/
    - name: npm i
      run: npm i
    - name: lint
      run: npm run build

  # Note: 以下は今後作る予定のアクションです。
  # lint-infra:
  #   runs-on: ubuntu-latest
  #   name: lint infra action
  #   steps:
  #   - name: Checkout
  #     uses: actions/checkout@v2-beta
  #   - name: catReadme
  #     run: cat ./README.md
  #   - name: echo
  #     run: echo "TODO:lintチェックを走らせる"
  # build-and-test-api:
  #   runs-on: ubuntu-latest
  #   name: build and test api action
  #   steps:
  #   - name: Checkout
  #     uses: actions/checkout@v2-beta
  #   - name: echo
  #     run: echo "TODO:build からの test コードを走らせる"
  # build-and-test-front:
  #   runs-on: ubuntu-latest
  #   name: build and test front action
  #   steps:
  #   - name: Checkout
  #     uses: actions/checkout@v2-beta
  #   - name: echo
  #     run: echo "TODO:build からの test コードを走らせる"
  # build-and-test-infra:
  #   runs-on: ubuntu-latest
  #   name: build and test infra action
  #   steps:
  #   - name: Checkout
  #     uses: actions/checkout@v2-beta
  #   - name: echo
  #     run: echo "TODO:build からの test コードを走らせる"

