name: "main actions"

on: [push]

jobs:
  check-api-job:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [10.x]
    name: check-api-job
    steps:
    - name: Checkout
      uses: actions/checkout@v2-beta
    - name: Setup Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: check api
      run: cd ./packages/api/ && npm install && npm run lint && npm run build && npm run test

  check-front-job:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [10.x]
    name: check-front-job
    steps:
    - name: Checkout
      uses: actions/checkout@v2-beta
    - name: Setup Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: front install
      run: cd ./packages/front/ && npm install
    - name: front lint
      run: cd ./packages/front/ && npm run lint
    - name: front build
      run: cd ./packages/front/ && npm run build

    # TODO: infraも適宜、構文追加や実行確認コマンドを追加する
    # - name: check front
    #   run: cd ./packages/front/ && npm install && npm run lint && npm run build

