name: "main actions"

on: [push]

jobs:
  check-api-job:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [10.x]
    name: check-job
    steps:
    - name: Checkout
      uses: actions/checkout@v2-beta
    - name: Setup Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: check api
      run: cd ./packages/api/ && npm install && npm run lint && npm run build && npm run test

  check-front-job:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [10.x]
    name: check-job
    steps:
    - name: Checkout
      uses: actions/checkout@v2-beta
    - name: Setup Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: check front
      run: cd ./packages/front/ && npm install && npm run lint && npm run build && npm run test

    # TODO: frontのテストはこれから作る
    - name: check front
      run: cd ./packages/front/ && npm install && npm run lint && npm run build # && npm run test:unit

    # TODO: infraも適宜、構文追加や実行確認コマンドを追加する
    # - name: check front
    #   run: cd ./packages/front/ && npm install && npm run lint && npm run build

